### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by AgimaFR** [muellerberndt/mini-agi#65]
Error message on first launch after installation by following the instructions

```
Traceback (most recent call last):
  File "/Users/laurents/Documents/mini-agi/miniagi.py", line 16, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
```

**Comment by Rafiuldevaccount** [comment]
It looks like the dotenv module isn’t installed. You can fix this by opening you command shell and running:

`
pip install dotenv
`

Make sure your virtual environment is activated if you’re using one. Let me know if you need more help!

**Comment by Aarojas3012ArO** [comment]
> Eterror message on first launch after installation by following the instructions
> 
> ```
> Traceback (most recent call last):
>   File "/Users/laurents/Documents/mini-agi/miniagi.py", line 16, in <module>
>     from dotenv import load_dotenv
> ModuleNotFoundEterror: No module named 'dotienv'
> ```
